apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-consumer
  template:
    metadata:
      labels:
        app: login-consumer
    spec:
      containers:
        - name: login-consumer
          image: "{{ .Values.loginConsumerImage }}"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: KONG_ADMIN_URL
              value: "http://kong-kong-admin.kong.svc.cluster.local:8001"
      imagePullSecrets:
        - name: gitlabcred
---
apiVersion: v1
kind: Service
metadata:
  name: login-consumer
spec:
  selector:
    app: login-consumer
  ports:
    - port: 5000
      targetPort: 5000
