apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-login-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-consumer
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
#   targetMemoryUtilizationPercentage: 80
