apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-get-request
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: get-request
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
#   targetMemoryUtilizationPercentage: 80
