apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-register-login
  annotations:
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: kong
  tls:
    - secretName: microservices-register-login
      hosts:
        - microservices.{{ .Values.nipIPAddress }}.nip.io
  rules:
    - host: microservices.{{ .Values.nipIPAddress }}.nip.io
      http:
        paths:
          - path: /register-consumer
            pathType: Prefix
            backend:
              service:
                name: register-consumer
                port:
                  number: 5000
          - path: /login-consumer
            pathType: Prefix
            backend:
              service:
                name: login-consumer
                port:
                  number: 5000
