apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  myDbUserPassword: mypassword
  myDbPaymentPassword: postgres
